timezones_list = [
    'Australian Central Daylight Savings Time (UTC+10:30)',
    'Australian Central Standard Time (UTC+09:30)',
    'Acre Time (UTC-05)',
    'ASEAN Common Time (UTC+06:30 - UTC+09)',
    'Atlantic Daylight Time (UTC-03)',
    'Australian Eastern Daylight Savings Time (UTC+11)',
    'Australian Eastern Standard Time (UTC+10)',
    'Afghanistan Time (UTC+04:30)',
    'Alaska Daylight Time (UTC-08)',
    'Alaska Standard Time (UTC-09)',
    'Amazon Summer Time (Brazil)[1] (UTC-03)',
    'Amazon Time (Brazil)[2] (UTC-04)',
    'Armenia Time (UTC+04)',
    'Argentina Time (UTC-03)',
    'Arabia Standard Time (UTC+03)',
    'Atlantic Standard Time (UTC-04)',
    'Australian Western Standard Time (UTC+08)',
    'Azores Summer Time (UTC±00)',
    'Azores Standard Time (UTC-01)',
    'Azerbaijan Time (UTC+04)',
    'Brunei Time (UTC+08)',
    'British Indian Ocean Time (UTC+06)',
    'Baker Island Time (UTC-12)',
    'Bolivia Time (UTC-04)',
    'Brasilia Summer Time (UTC-02)',
    'Brasilia Time (UTC-03)',
    'Bangladesh Standard Time (UTC+06)',
    'Bougainville Standard Time[3] (UTC+11)',
    'British Summer Time (British Standard Time from Feb 1968 to Oct 1971) '
    '(UTC+01)',
    'Bhutan Time (UTC+06)',
    'Central Africa Time (UTC+02)',
    'Cocos Islands Time (UTC+06:30)',
    'Central Daylight Time (North America) (UTC-05)',
    'Cuba Daylight Time[4] (UTC-04)',
    'Central European Summer Time (Cf. HAEC) (UTC+02)',
    'Central European Time (UTC+01)',
    'Chatham Daylight Time (UTC+13:45)',
    'Chatham Standard Time (UTC+12:45)',
    'Choibalsan Standard Time (UTC+08)',
    'Choibalsan Summer Time (UTC+09)',
    'Chamorro Standard Time (UTC+10)',
    'Chuuk Time (UTC+10)',
    'Clipperton Island Standard Time (UTC-08)',
    'Central Indonesia Time (UTC+08)',
    'Cook Island Time (UTC-10)',
    'Chile Summer Time (UTC-03)',
    'Chile Standard Time (UTC-04)',
    'Colombia Summer Time (UTC-04)',
    'Colombia Time (UTC-05)',
    'Central Standard Time (North America) (UTC-06)',
    'China Standard Time (UTC+08)',
    'Central Standard Time (Australia) (UTC+09:30)',
    'Central Summer Time (Australia) (UTC+10:30)',
    'Cuba Standard Time (UTC-05)',
    'China time (UTC+08)',
    'Cape Verde Time (UTC-01)',
    'Central Western Standard Time (Australia) unofficial (UTC+08:45)',
    'Christmas Island Time (UTC+07)',
    'Davis Time (UTC+07)',
    "Dumont d'Urville Time (UTC+10)",
    'AIX specific equivalent of Central European Time[5] (UTC+01)',
    'Easter Island Summer Time (UTC-05)',
    'Easter Island Standard Time (UTC-06)',
    'East Africa Time (UTC+03)',
    'Eastern Caribbean Time (does not recognise DST) (UTC-04)',
    'Ecuador Time (UTC-05)',
    'Eastern Daylight Time (North America) (UTC-04)',
    'Eastern Summer Time (Australia) (UTC+11)',
    'Eastern European Summer Time (UTC+03)',
    'Eastern European Time (UTC+02)',
    'Eastern Greenland Summer Time (UTC±00)',
    'Eastern Greenland Time (UTC-01)',
    'Eastern Indonesian Time (UTC+09)',
    'Eastern Standard Time (North America) (UTC-05)',
    'Eastern Standard Time (Australia) (UTC+10)',
    'Further-eastern European Time (UTC+03)',
    'Fiji Time (UTC+12)',
    'Falkland Islands Summer Time (UTC-03)',
    'Falkland Islands Time (UTC-04)',
    'Fernando de Noronha Time (UTC-02)',
    'Galapagos Time (UTC-06)',
    'Gambier Islands (UTC-09)',
    'Georgia Standard Time (UTC+04)',
    'French Guiana Time (UTC-03)',
    'Gilbert Island Time (UTC+12)',
    'Gambier Island Time (UTC-09)',
    'Greenwich Mean Time (UTC±00)',
    'South Georgia and the South Sandwich Islands (UTC-02)',
    'Gulf Standard Time (UTC+04)',
    'Guyana Time (UTC-04)',
    'Hawaii-Aleutian Daylight Time (UTC-09)',
    "Heure Avancée d'Europe Centrale francised name for CEST (UTC+02)",
    'Hawaii-Aleutian Standard Time (UTC-10)',
    'Hong Kong Time (UTC+08)',
    'Heard and McDonald Islands Time (UTC+05)',
    'Khovd Summer Time (UTC+08)',
    'Khovd Standard Time (UTC+07)',
    'Indochina Time (UTC+07)',
    'Israel Daylight Time (UTC+03)',
    'Indian Ocean Time (UTC+03)',
    'Iran Daylight Time (UTC+04:30)',
    'Irkutsk Time (UTC+08)',
    'Iran Standard Time (UTC+03:30)',
    'Indian Standard Time (UTC+05:30)',
    'Irish Standard Time[6] (UTC+01)',
    'Israel Standard Time (UTC+02)',
    'Japan Standard Time (UTC+09)',
    'Kyrgyzstan time (UTC+06)',
    'Kosrae Time (UTC+11)',
    'Krasnoyarsk Time (UTC+07)',
    'Korea Standard Time (UTC+09)',
    'Lord Howe Standard Time (UTC+10:30)',
    'Lord Howe Summer Time (UTC+11)',
    'Line Islands Time (UTC+14)',
    'Magadan Time (UTC+12)',
    'Mawson Station Time (UTC+05)',
    'Mountain Daylight Time (North America) (UTC-06)',
    'Middle European Time Same zone as CET (UTC+01)',
    'Middle European Summer Time Same zone as CEST (UTC+02)',
    'Marshall Islands (UTC+12)',
    'Macquarie Island Station Time (UTC+11)',
    'Marquesas Islands Time (UTC-09:30)',
    'Myanmar Standard Time (UTC+06:30)',
    'Moscow Time (UTC+03)',
    'Malaysia Standard Time (UTC+08)',
    'Mountain Standard Time (North America) (UTC-07)',
    'Mauritius Time (UTC+04)',
    'Maldives Time (UTC+05)',
    'Malaysia Time (UTC+08)',
    'New Caledonia Time (UTC+11)',
    'Newfoundland Daylight Time (UTC-02:30)',
    'Norfolk Time (UTC+11)',
    'Nepal Time (UTC+05:45)',
    'Newfoundland Standard Time (UTC-03:30)',
    'Newfoundland Time (UTC-03:30)',
    'Niue Time (UTC-11)',
    'New Zealand Daylight Time (UTC+13)',
    'New Zealand Standard Time (UTC+12)',
    'Omsk Time (UTC+06)',
    'Oral Time (UTC+05)',
    'Pacific Daylight Time (North America) (UTC-07)',
    'Peru Time (UTC-05)',
    'Kamchatka Time (UTC+12)',
    'Papua New Guinea Time (UTC+10)',
    'Phoenix Island Time (UTC+13)',
    'Philippine Time (UTC+08)',
    'Pakistan Standard Time (UTC+05)',
    'Saint Pierre and Miquelon Daylight time (UTC-02)',
    'Saint Pierre and Miquelon Standard Time (UTC-03)',
    'Pohnpei Standard Time (UTC+11)',
    'Pacific Standard Time (North America) (UTC-08)',
    'Philippine Standard Time (UTC+08)',
    'Paraguay Summer Time (South America)[7] (UTC-03)',
    'Paraguay Time (South America)[8] (UTC-04)',
    'Réunion Time (UTC+04)',
    'Rothera Research Station Time (UTC-03)',
    'Sakhalin Island time (UTC+11)',
    'Samara Time (UTC+04)',
    'South African Standard Time (UTC+02)',
    'Solomon Islands Time (UTC+11)',
    'Seychelles Time (UTC+04)',
    'Singapore Time (UTC+08)',
    'Sri Lanka Standard Time (UTC+05:30)',
    'Srednekolymsk Time (UTC+11)',
    'Suriname Time (UTC-03)',
    'Samoa Standard Time (UTC-11)',
    'Singapore Standard Time (UTC+08)',
    'Showa Station Time (UTC+03)',
    'Tahiti Time (UTC-10)',
    'Thailand Standard Time (UTC+07)',
    'Indian/Kerguelen (UTC+05)',
    'Tajikistan Time (UTC+05)',
    'Tokelau Time (UTC+13)',
    'Timor Leste Time (UTC+09)',
    'Turkmenistan Time (UTC+05)',
    'Turkey Time (UTC+03)',
    'Tonga Time (UTC+13)',
    'Tuvalu Time (UTC+12)',
    'Ulaanbaatar Summer Time (UTC+09)',
    'Ulaanbaatar Standard Time (UTC+08)',
    'Kaliningrad Time (UTC+02)',
    'Coordinated Universal Time (UTC±00)',
    'Uruguay Summer Time (UTC-02)',
    'Uruguay Standard Time (UTC-03)',
    'Uzbekistan Time (UTC+05)',
    'Venezuelan Standard Time (UTC-04)',
    'Vladivostok Time (UTC+10)',
    'Volgograd Time (UTC+04)',
    'Vostok Station Time (UTC+06)',
    'Vanuatu Time (UTC+11)',
    'Wake Island Time (UTC+12)',
    'West Africa Summer Time (UTC+02)',
    'West Africa Time (UTC+01)',
    'Western European Summer Time (UTC+01)',
    'Western European Time (UTC±00)',
    'Western Indonesian Time (UTC+07)',
    'Western Standard Time (UTC+08)',
    'Yakutsk Time (UTC+09)',
    'Yekaterinburg Time (UTC+05)'
]
TIMEZONE_CHOICES = tuple([(tz, tz) for tz in timezones_list])
